name: subitoo
version: '0.1'
summary: python subitoo package
description: "Price tracker and crawler for Subito.it"

base: core22
grade: stable
confinement: strict

apps:
  subitoo:
    command: bin/subitoo-cmd
    plugs: [network]
parts:
  subitoo:
    plugin: python
    source: .
    python-requirements:
      - src/requirements.txt
